name: Update README images

on:
  schedule:
    - cron: "0 3 * * *" # هر روز ساعت 3 صبح اجرا می‌شود
  workflow_dispatch: # امکان اجرای دستی

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: techcodeco
          token: ${{ secrets.GITHUB_TOKEN }}
          file: images/trophy.svg
          theme: radical
          max-rows: 1
          column: 7

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add images/*.svg
          git commit -m "Update trophy images" || exit 0
          git push
